# FPS counter GStreamer plugin

mode = shared_obj

LIBS += -ltimeutil

CXXFLAGS += -Wno-unused-parameter -Wno-unused-local-typedefs

INCLUDES += `pkg-config --cflags gstPluginWrap`
LIBS += `pkg-config --libs gstPluginWrap`

ifeq ($(cfg), release)
	BIN_DIR = ../bin
endif
