# Dummy GStreamer plugin

mode = shared_obj

CXXFLAGS += -Wno-unused-parameter -Wno-unused-local-typedefs

INCLUDES += `pkg-config --cflags gstreamer-0.10`
LIBS += `pkg-config --libs gstreamer-0.10`

ifeq ($(cfg), release)
	BIN_DIR = ../bin
endif
